name: Create Pull Request

on:
  repository_dispatch:
    types: [create-pr]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        pr_title: ${{ github.event.client_payload.pr_title }}
        pr_body: ${{ github.event.client_payload.pr_description }}
        source_branch: ${{ github.event.client_payload.branch }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
