name: Create Pull Request

on:
  repository_dispatch:
    types: [create-pr]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2.8.0
      with:
        title: ${{ github.event.client_payload.pr_title }}
        body: ${{ github.event.client_payload.pr_description }}
        base: master
        branch: ${{ github.event.client_payload.branch }}
