name: create or update release

on:
  repository_dispatch:
    types: [create-github-release]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: ${{ github.event.client_payload.commitish }}
        tag: ${{ github.event.client_payload.tag_name }}
        name: ${{ github.event.client_payload.release_name }}
        body: ${{ github.event.client_payload.release_description }}
        prerelease: ${{ github.event.client_payload.prerelease }}
        allowUpdates: ${{ github.event.client_payload.allow_update }}
