name: Create Pull Request

on:
  repository_dispatch:
    types: [create-pr]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create pull request for ${{ github.event.client_payload.image_version }}
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.pulls.create({
            owner: "akv-platform",
            repo: "windows-documentation",
            title: "Test PR",
            head: "release-branch",
            base: "master",
            body: "PR description"
          });
