name: Create Pull Request

on:
  repository_dispatch:
    types: [create-pr]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print payload
      run: echo ${{ github.event.client_payload.message }}
