name: create or update release

on:
  repository_dispatch:
    types: [create-github-release]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commitish: ${{ github.event.client_payload.commitish }}
        tag: ${{ github.event.client_payload.tag }}
        name: ${{ github.event.client_payload.release_name }}
        body: ${{ github.event.client_payload.release_description }}
        prerelease: ${{ github.event.client_payload.prerelease }}
        allow_override: ${{ github.event.client_payload.allow_override }}
