name: create or update release

on:
  repository_dispatch:
    types: [create-github-release]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commitish: "a5f78f1c793b7c4bd08eba6905bbc70771b1e402"
        tag: "v1.2.3"
        name: "Test release"
        body: ${{ github.event.client_payload.release_description }}
        prerelease: "true"
        allow_override: "true"
